openapi: 3.0.0
info:
  title: ERPNext Indonesia Localization API
  description: Regional API for Indonesian Address and Tax Logic.
  version: 1.2.0
servers:
  - url: http://site1.localhost:8000/api/method
    description: Local Development Server

paths:
  /erpnext_indonesia_localization.api.get_provinces:
    get:
      summary: Get Provinces
      responses:
        "200":
          description: List of Provinces

  /erpnext_indonesia_localization.api.get_regencies:
    get:
      summary: Get Regencies/Kabupaten
      parameters:
        - name: province_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of Regencies

  /erpnext_indonesia_localization.api.get_districts:
    get:
      summary: Get Districts/Kecamatan
      parameters:
        - name: regency_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of Districts

  /erpnext_indonesia_localization.api.get_villages:
    get:
      summary: Get Villages/Kelurahan
      parameters:
        - name: district_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of Villages
